### 회원 가입
POST localhost:8080/users/signup
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "asdF1224$",
  "role" : "USER"
}

### 로그인
POST localhost:8080/users/login
Content-Type: application/json

{
  "email": "test@naver.com",
  "password": "asdF1224$"
}

### 회원 탈퇴
PATCH localhost:8080/users/{{userId}}
Content-Type: application/json

{
  "password": "asdF1224$"
}

### 가게 생성
POST localhost:8080/stores
Content-Type: application/json

{
  "storeName": "삼성",
  "openTime": "10:00",
  "closeTime": "11:00",
  "minOrderPrice": 10000
}

### 가게 수정
PATCH localhost:8080/stores/{{storeId}}
Content-Type: application/json

{
  "storeName": "삼성전자",
  "openTime": "HH:MM",
  "closeTime": "HH:MM",
  "minOrderPrice": 10000
}

### 가게 단건 조회
GET localhost:8080/stores/{{storeId}}

### 가게 다건 조회
GET localhost:8080/stores

### 가게 폐업
DELETE localhost:8080/stores/{{storeId}}

### 메뉴 생성
POST localhost:8080/menus
Content-Type: application/json

{
  "storeId" : 1,
  "menuName" : "삼선짬뽕",
  "price" : 12000
}

### 메뉴 수정
PATCH localhost:8080/menus/{{menuId}}
Content-Type: application/json

{
  "storeId": "1",
  "menuName" : "쟁반짜장",
  "price" : 12000
}

### 메뉴 삭제
DELETE localhost:8080/menus/{{menuId}}

### 메뉴 주문
POST localhost:8080/orders
Content-Type: application/json

{
  "storeId" : 1,
  "menuId" : 1,
  "quantity" : 2,
  "address" : "서울특별시 경복궁 4번 출구"
}

### 주문 상태 변경
PATCH localhost:8080/orders/status=ACCEPT_ORDER

### 리뷰 생성
POST localhost:8080/reviews
Content-Type: application/json

{
  "orderId" : 1,
  "content" : "음식이 친절해요",
  "rating" : 5
}

### 리뷰 생성일자 기준 조회
GET localhost:8080/reviews?storeId=1&sort=rating

### 장바구니 조회 - 장바구니 생성 전에 데이터가 있는 지 없는 지 확인
GET localhost:8080/cart

### 장바구니 생성
POST localhost:8080/cart?userId=1&storeId=1
Content-Type: application/json

{
  "menuName": "삼선짬뽕",
  "quantity": 3,
  "price" : 12000
}

### 장바구니 수정
PUT localhost:8080/cart?userId=1&storeId=1
Content-Type: application/json

{
  "menuName": "쟁반짜장",
  "quantity": 4,
  "price" : 12000
}

### 장바구니 새로운 메뉴 추가
POST localhost:8080/cart/item??userId=1&storeId=1
Content-Type: application/json

{
  "menuName": "치킨",
  "quantity": 2,
  "price" : 24000
}

### 장바구니 전체 삭제
DELETE localhost:8080/cart

### 특정유저 누적 포인트
GET localhost:8080/point/{{userId}}

### 쿠폰 생성
POST localhost:8080/coupon/create
Content-Type: application/json

{
  "storeId": 1,
  "couponType": "FIXED_AMOUNT",
  "discount": 5000,
  "maxIssued": 3,
  "expiredAt": "2024-11-25"
}

### 쿠폰 발급
POST localhost:8080/coupon/issued
Content-Type: application/json

{
  "userId": 1,
  "storeId": 1,
  "couponId": 1
}

### 어드민 회원가입
POST localhost:8080/users/signup
Content-Type: application/json

{
    "email" : "admin@naver.com",
    "password" : "Asdf1234%",
    "role" : "ADMIN"
}

### 어드민 로그인
POST localhost:8080/users/login
Content-Type: application/json

{
  "email" : "admin@naver.com",
  "password" : "Asdf1234%"
}

### 전체 일간 주문 건수/총액 조회
GET localhost:8080/dashboard/orders/daily-summary?date=2024-12-08
Content-Type: application/json

### 전체 월간 주문 건수/총액 조회
GET localhost:8080/dashboard/orders/monthly-summary?month=2024-12
Content-Type: application/json

### 가게별 일간 주문 건수/총액 조회
GET localhost:8080/dashboard/stores/orders/daily-summary?date=2024-12-08
Content-Type: application/json

### 가게별 월간 주문 건수/총액 조회
GET localhost:8080/dashboard/stores/orders/monthly-summary?month=2024-12
Content-Type: application/json

### 카테고리별 일간 주문 건수/총액 조회
GET localhost:8080/dashboard/category/orders/daily-summary?date=2024-12-08
Content-Type: application/json

### 카테고리별 월간 주문 건수/총액 조회
GET localhost:8080/dashboard/category/orders/monthly-summary?month=2024-12
Content-Type: application/json
